using System; using NUnit.Framework; using PortalNes.Emulator.Cartridge;
namespace PortalNes.Tests
{
    public sealed class INesLoaderTests
    {
        [TestCase(1, 16384)] [TestCase(2, 32768)] public void Load_ValidNrom(int banks, int size) { var c = INesLoader.Load(Rom(banks, 1, 1)); Assert.That(c.MapperNumber, Is.Zero); Assert.That(c.PrgRom.Length, Is.EqualTo(size)); Assert.That(c.ChrRom.Length, Is.EqualTo(8192)); Assert.That(c.Mirroring, Is.EqualTo(MirroringMode.Vertical)); }
        [Test] public void Load_Trainer_SkipsBytes() { var r = Rom(1, 1, 4); r[528] = 0xA5; Assert.That(INesLoader.Load(r).PrgRom[0], Is.EqualTo(0xA5)); }
        [Test] public void Load_InvalidMagic_Throws() { var r = Rom(1, 1); r[0] = 0; Assert.That(() => INesLoader.Load(r), Throws.TypeOf<INesFormatException>().With.Message.Contains("magic")); }
        [Test] public void Load_UnsupportedMapper_Throws() { Assert.That(() => INesLoader.Load(Rom(2, 1, 0x60)), Throws.TypeOf<NotSupportedException>().With.Message.Contains("Mapper 6")); }
        [Test] public void Load_ChrRam_Throws() { Assert.That(() => INesLoader.Load(Rom(1, 0)), Throws.TypeOf<NotSupportedException>().With.Message.Contains("8KB CHR ROM")); }
        [Test] public void Load_Mapper2WithChrRam() { var c = INesLoader.Load(Rom(4, 0, 0x20)); Assert.That(c.MapperNumber, Is.EqualTo(2)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.ChrRom.Length, Is.EqualTo(8192)); }
        [Test] public void Load_Mapper1WithChrRam() { var c = INesLoader.Load(Rom(4, 0, 0x10)); Assert.That(c.MapperNumber, Is.EqualTo(1)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper001>()); }
        [Test] public void Load_Mapper3WithChrBanks() { var c = INesLoader.Load(Rom(2, 4, 0x30)); Assert.That(c.MapperNumber, Is.EqualTo(3)); Assert.That(c.HasChrRam, Is.False); Assert.That(c.ChrRom.Length, Is.EqualTo(32768)); }
        [Test] public void Load_Mapper4WithChrBanks() { var c = INesLoader.Load(Rom(8, 8, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(4)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper004>()); }
        [Test] public void Load_Mapper7WithChrRam() { var c = INesLoader.Load(Rom(4, 0, 0x70)); Assert.That(c.MapperNumber, Is.EqualTo(7)); Assert.That(c.HasChrRam, Is.True); }
        [Test] public void Load_Mapper9WithChrBanks() { var c = INesLoader.Load(Rom(4, 8, 0x90)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper009>()); }
        [Test] public void Load_Mapper10WithChrBanks() { var c = INesLoader.Load(Rom(8, 8, 0xA0)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper010>()); }
        [Test] public void Load_Mapper18WithChrBanks() { var c = INesLoader.Load(Rom(16, 16, 0x20, 0x10)); Assert.That(c.MapperNumber, Is.EqualTo(18)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper018>()); }
        [Test] public void Load_Mapper19WithChrBanks() { var c = INesLoader.Load(Rom(16, 32, 0x30, 0x10)); Assert.That(c.MapperNumber, Is.EqualTo(19)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper019>()); }
        [Test] public void Load_Mapper21WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0x50, 0x10)); Assert.That(c.MapperNumber, Is.EqualTo(21)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper021>()); }
        [Test] public void Load_Mapper22WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0x60, 0x10)); Assert.That(c.MapperNumber, Is.EqualTo(22)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper022>()); }
        [Test] public void Load_Mapper23WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0x70, 0x10)); Assert.That(c.MapperNumber, Is.EqualTo(23)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper023>()); }
        [Test] public void Load_Mapper24WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0x80, 0x10)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper024>()); }
        [Test] public void Load_Mapper25WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0x90, 0x10)); Assert.That(c.MapperNumber, Is.EqualTo(25)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper025>()); }
        [Test] public void Load_Mapper26WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0xA0, 0x10)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper026>()); }
        [Test] public void Load_Mapper32WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0x00, 0x20)); Assert.That(c.MapperNumber, Is.EqualTo(32)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper032>()); }
        [Test] public void Load_Mapper33WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0x10, 0x20)); Assert.That(c.MapperNumber, Is.EqualTo(33)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper033>()); }
        [Test] public void Load_Mapper65WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x10, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(65)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper065>()); }
        [Test] public void Load_Mapper48WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x00, 0x30)); Assert.That(c.MapperNumber, Is.EqualTo(48)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper048>()); }
        [Test] public void Load_Mapper66WithBanks() { var c = INesLoader.Load(Rom(4, 2, 0x20, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(66)); Assert.That(c.PrgRom.Length, Is.EqualTo(65536)); Assert.That(c.ChrRom.Length, Is.EqualTo(16384)); }
        [Test] public void Load_Mapper67WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x30, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(67)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper067>()); }
        [Test] public void Load_Mapper68WithBanks() { var c = INesLoader.Load(Rom(8, 32, 0x40, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(68)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper068>()); }
        [Test] public void Load_Mapper69WithBanks() { var c = INesLoader.Load(Rom(16, 32, 0x50, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(69)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper069>()); }
        [Test] public void Load_Mapper70WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x60, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(70)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper070>()); }
        [Test] public void Load_Mapper5WithChrRam() { var c = INesLoader.Load(Rom(8, 0, 0x50, 0x00)); Assert.That(c.MapperNumber, Is.EqualTo(5)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper005>()); }
        [Test] public void Load_Mapper71WithChrRam() { var c = INesLoader.Load(Rom(8, 0, 0x70, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(71)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper071>()); }
        [Test] public void Load_Mapper72WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x80, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(72)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper072>()); }
        [Test] public void Load_Mapper73WithChrRam() { var c = INesLoader.Load(Rom(8, 0, 0x90, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(73)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper073>()); }
        [Test] public void Load_Mapper75WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0xB0, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(75)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper075>()); }
        [Test] public void Load_Mapper76WithChrBanks() { var c = INesLoader.Load(Rom(8, 16, 0xC0, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(76)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper076>()); }
        [Test] public void Load_LegacyMapper78HolyDiverBoard() { var c = INesLoader.Load(Rom(8, 16, 0xE0, 0x40)); Assert.That(c.MapperNumber, Is.EqualTo(78)); Assert.That(((PortalNes.Emulator.Mappers.Mapper078)c.Mapper).UsesHolyDiverMirroring, Is.True); }
        [Test] public void Load_LegacyMapper78CosmoCarrierBoard() { var c = INesLoader.Load(Rom(8, 16, 0xE8, 0x40)); Assert.That(((PortalNes.Emulator.Mappers.Mapper078)c.Mapper).UsesHolyDiverMirroring, Is.False); }
        [Test] public void Load_Mapper80WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x00, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(80)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper080>()); }
        [Test] public void Load_Mapper85WithChrRam() { var c = INesLoader.Load(Rom(16, 0, 0x50, 0x50)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper085>()); }
        [Test] public void Load_Mapper86WithBanks() { var c = INesLoader.Load(Rom(8, 8, 0x60, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(86)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper086>()); }
        [Test] public void Load_Mapper87WithBanks() { var c = INesLoader.Load(Rom(2, 4, 0x70, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(87)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper087>()); }
        [Test] public void Load_Mapper88WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x80, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(88)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper088>()); }
        [Test] public void Load_Mapper89WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0x90, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(89)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper089>()); }
        [Test] public void Load_Mapper93WithChrRam() { var c = INesLoader.Load(Rom(8, 0, 0xD0, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(93)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper093>()); }
        [Test] public void Load_LegacyMapper88FourScreenHeaderAsMapper154() { var c = INesLoader.Load(Rom(8, 16, 0x89, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(154)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper154>()); }
        [Test] public void Load_Mapper95WithBanks() { var c = INesLoader.Load(Rom(8, 4, 0xF0, 0x50)); Assert.That(c.MapperNumber, Is.EqualTo(95)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper095>()); }
        [Test] public void Load_Mapper97WithChrRam() { var c = INesLoader.Load(Rom(16, 0, 0x10, 0x60)); Assert.That(c.MapperNumber, Is.EqualTo(97)); Assert.That(c.HasChrRam, Is.True); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper097>()); }
        [Test] public void Load_Mapper140WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0xC0, 0x80)); Assert.That(c.MapperNumber, Is.EqualTo(140)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper140>()); }
        [Test] public void Load_Mapper154WithBanks() { var c = INesLoader.Load(Rom(8, 16, 0xA0, 0x90)); Assert.That(c.MapperNumber, Is.EqualTo(154)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper154>()); }
        [Test] public void Load_Mapper154IgnoresFourScreenHeaderFlag() { var c = INesLoader.Load(Rom(8, 16, 0xA8, 0x90)); Assert.That(c.MapperNumber, Is.EqualTo(154)); Assert.That(c.Mapper.MirroringOverride, Is.EqualTo(MirroringMode.SingleScreenLower)); }
        [Test] public void Load_Mapper184WithBanks() { var c = INesLoader.Load(Rom(2, 4, 0x80, 0xB0)); Assert.That(c.MapperNumber, Is.EqualTo(184)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper184>()); }
        [Test] public void Load_Mapper206WithBanks() { var c = INesLoader.Load(Rom(8, 8, 0xE0, 0xC0)); Assert.That(c.MapperNumber, Is.EqualTo(206)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper206>()); }
        [Test] public void Load_Mapper210WithBanks() { var c = INesLoader.Load(Rom(16, 16, 0x20, 0xD0)); Assert.That(c.MapperNumber, Is.EqualTo(210)); Assert.That(c.HeaderMapperNumber, Is.EqualTo(210)); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper210>()); }
        [Test] public void Load_Mapper7RejectsHalfPrgBank() { Assert.That(() => INesLoader.Load(Rom(3, 0, 0x70)), Throws.TypeOf<NotSupportedException>().With.Message.Contains("32KB")); }
        [Test] public void Load_RegionFromTvSystemFlag() { var r=Rom(1,1); r[9]=1; Assert.That(INesLoader.Load(r).Region, Is.EqualTo(NesRegion.Pal)); }
        [Test] public void Load_RegionOverrideWinsOverHeader() { var r=Rom(1,1); Assert.That(INesLoader.Load(r, NesRegion.Pal).Region, Is.EqualTo(NesRegion.Pal)); }
        [Test] public void Load_DiskDudeHeader_IgnoresFalseMapperHighBitsAndPalFlag() { var r=Rom(2,4,0x30); var s="DiskDude!"; for(int i=0;i<s.Length;i++) r[7+i]=(byte)s[i]; var c=INesLoader.Load(r); Assert.That(c.MapperNumber, Is.EqualTo(3)); Assert.That(c.HeaderMapperNumber, Is.EqualTo(3)); Assert.That(c.Region, Is.EqualTo(NesRegion.Ntsc)); }
        [Test] public void Load_Nes20StandardMapper() { var r=Rom(8,8,0x40,0x08); var c=INesLoader.Load(r); Assert.That(c.MapperNumber, Is.EqualTo(4)); Assert.That(c.SubmapperNumber, Is.Zero); Assert.That(c.Mapper, Is.TypeOf<PortalNes.Emulator.Mappers.Mapper004>()); }
        [Test] public void Load_Nes20RegionUsesByte12() { var r=Rom(2,4,0x30,0x08); r[12]=1; Assert.That(INesLoader.Load(r).Region, Is.EqualTo(NesRegion.Pal)); }
        [Test] public void Load_Nes20ChrRamUsesDeclaredSize() { var r=Rom(4,0,0x20,0x08); r[11]=7; var c=INesLoader.Load(r); Assert.That(c.HasChrRam, Is.True); Assert.That(c.ChrRom.Length, Is.EqualTo(8192)); }
        [Test] public void Load_Nes20MissingChrRamDeclarationThrows() { var r=Rom(4,0,0x20,0x08); Assert.That(() => INesLoader.Load(r), Throws.TypeOf<NotSupportedException>().With.Message.Contains("CHR RAM")); }
        [Test] public void Load_Nes20Mapper3Submapper1DisablesBusConflicts() { var r=Rom(2,4,0x30,0x08); r[8]=0x10; for(int bank=0;bank<4;bank++) r[16+32768+bank*8192]=(byte)bank; var c=INesLoader.Load(r); c.Mapper.CpuWrite(0x8000,3); Assert.That(c.SubmapperNumber, Is.EqualTo(1)); Assert.That(c.Mapper.PpuRead(0), Is.EqualTo(3)); }
        [Test] public void Load_Nes20Mapper32Submapper1UsesMajorLeagueBoard() { var r=Rom(8,16,0x00,0x28); r[8]=0x10; var c=INesLoader.Load(r); Assert.That(c.SubmapperNumber, Is.EqualTo(1)); Assert.That(c.Mapper.MirroringOverride, Is.EqualTo(MirroringMode.SingleScreenUpper)); }
        [Test] public void Load_Nes20Mapper70Submapper1DisablesBusConflicts() { var r=Rom(8,16,0x60,0x48); r[8]=0x10; var c=INesLoader.Load(r); Assert.That(((PortalNes.Emulator.Mappers.Mapper070)c.Mapper).HasBusConflicts, Is.False); }
        [TestCase(1, false)] [TestCase(3, true)] public void Load_Nes20Mapper78SubmapperSelectsBoard(int submapper, bool holyDiver) { var r=Rom(8,16,0xE0,0x48); r[8]=(byte)(submapper<<4); var c=INesLoader.Load(r); Assert.That(((PortalNes.Emulator.Mappers.Mapper078)c.Mapper).UsesHolyDiverMirroring, Is.EqualTo(holyDiver)); }
        [Test] public void Load_Nes20UnsupportedSubmapperThrowsClearly() { var r=Rom(8,8,0x40,0x08); r[8]=0x10; Assert.That(() => INesLoader.Load(r), Throws.TypeOf<NotSupportedException>().With.Message.Contains("Submapper 1")); }
        private static byte[] Rom(int p, int c, byte f6=0, byte f7=0) { int t=(f6&4)!=0?512:0; var r=new byte[16+t+p*16384+c*8192]; r[0]=(byte)'N';r[1]=(byte)'E';r[2]=(byte)'S';r[3]=0x1A;r[4]=(byte)p;r[5]=(byte)c;r[6]=f6;r[7]=f7;return r; }
    }
}
